apiVersion: runtime.cluster.x-k8s.io/v1alpha1
kind: ExtensionConfig
metadata:
  annotations:
    runtime.cluster.x-k8s.io/inject-ca-from-secret: default/win-service-cert
  name: windowsext
  namespace: default
spec:
  clientConfig:
    service:
      name: win-service
      namespace: default
      port: 443
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values:
      - default
