apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: windows-webhook
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/part-of: windows-webhook
  name: windows-webhook-controller-manager
  namespace: windows-webhook-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: windows-webhook
    app.kubernetes.io/instance: leader-election-role
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: role
    app.kubernetes.io/part-of: windows-webhook
  name: windows-webhook-leader-election-role
  namespace: windows-webhook-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: windows-webhook-manager-role
rules:
- apiGroups:
  - windows.windows.k8s.io
  resources:
  - hypervs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - windows.windows.k8s.io
  resources:
  - hypervs/finalizers
  verbs:
  - update
- apiGroups:
  - windows.windows.k8s.io
  resources:
  - hypervs/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: windows-webhook
    app.kubernetes.io/instance: metrics-reader
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: windows-webhook
  name: windows-webhook-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: windows-webhook
    app.kubernetes.io/instance: proxy-role
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: windows-webhook
  name: windows-webhook-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: windows-webhook
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: windows-webhook
  name: windows-webhook-leader-election-rolebinding
  namespace: windows-webhook-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: windows-webhook-leader-election-role
subjects:
- kind: ServiceAccount
  name: windows-webhook-controller-manager
  namespace: windows-webhook-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: windows-webhook
    app.kubernetes.io/instance: manager-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: windows-webhook
  name: windows-webhook-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: windows-webhook-manager-role
subjects:
- kind: ServiceAccount
  name: windows-webhook-controller-manager
  namespace: windows-webhook-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: windows-webhook
    app.kubernetes.io/instance: proxy-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: windows-webhook
  name: windows-webhook-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: windows-webhook-proxy-role
subjects:
- kind: ServiceAccount
  name: windows-webhook-controller-manager
  namespace: windows-webhook-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: windows-webhook
    app.kubernetes.io/instance: controller-manager-metrics-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: windows-webhook
    control-plane: controller-manager
  name: windows-webhook-controller-manager-metrics-service
  namespace: windows-webhook-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: windows-webhook
    app.kubernetes.io/instance: webhook-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hyperv
    app.kubernetes.io/part-of: windows-webhook
  name: windows-webhook-webhook-service
  namespace: windows-webhook-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: windows-webhook
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: deployment
    app.kubernetes.io/part-of: windows-webhook
    control-plane: controller-manager
  name: windows-webhook-controller-manager
  namespace: windows-webhook-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
                - ppc64le
                - s390x
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=0
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        command:
        - /manager
        image: sigwindowstools/hyperv-runtimeclass-mutating-webhook:latest
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      securityContext:
        runAsNonRoot: true
      serviceAccountName: windows-webhook-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: windows-webhook
    app.kubernetes.io/instance: serving-cert
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: certificate
    app.kubernetes.io/part-of: windows-webhook
  name: windows-webhook-serving-cert
  namespace: windows-webhook-system
spec:
  dnsNames:
  - windows-webhook-webhook-service.windows-webhook-system.svc
  - windows-webhook-webhook-service.windows-webhook-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: windows-webhook-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: windows-webhook
    app.kubernetes.io/instance: selfsigned-issuer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: issuer
    app.kubernetes.io/part-of: windows-webhook
  name: windows-webhook-selfsigned-issuer
  namespace: windows-webhook-system
spec:
  selfSigned: {}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: windows-webhook-system/windows-webhook-serving-cert
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: windows-webhook
    app.kubernetes.io/instance: mutating-webhook-configuration
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mutatingwebhookconfiguration
    app.kubernetes.io/part-of: windows-webhook
  name: windows-webhook-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: windows-webhook-webhook-service
      namespace: windows-webhook-system
      path: /mutate-v1-pod
    caBundle: |
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURMekNDQWhlZ0F3SUJBZ0lVUnBOMHU0c3NqbFV5
      OUxHMFlaWnAxdXdLczVrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0p6RUxNQWtHQTFVRUJoTUNRVlV4R0RB
      V0JnTlZCQU1NRDNkcGJtUnZkM010ZDJWaWFHOXZhekFlRncweQpNekV3TWpRd05qQTJNVFZhRncweU5E
      RXdNak13TmpBMk1UVmFNQ2N4Q3pBSkJnTlZCQVlUQWtGVk1SZ3dGZ1lEClZRUUREQTkzYVc1a2IzZHpM
      WGRsWW1odmIyc3dnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUsKQW9JQkFRQ25jcm9M
      S1ViZ3k5U2hVYkNMZTBDQXZKcFBreTE0L3pSWWh3ZlVjdGRadGY5aEt0MkYvL1BtL1AvLwpxRHRnYzR4
      YlRPZnY3bWd6Rk56MTlJbzY1dHBuQmpmSmNNbm1iUzNTQ0VqUXdheTBMQ2hocUtyTlp0K0duY29oClB5
      NDArRG5nZm9SamFxTmdLT2xPL1hYNzRZTDFBdWw1SkVLTnFZSVlaRVpEaTRWVmxUWGsyL0xrdUhFYmJl
      ME4KR25MNDlvQzhsczFUTVhDcDBISkgwOGpUZDZFVm04WWZDYUNTemZwYkZuNUNBMVdyN0ZvZjhRQjJq
      STJlZUlPVgpNeGxOcm1WOFRMTGFxeHlyWmthbUN6YVlpdGRQSVlocnZsUVYvTERtNGJRYU8rZ21mTnY3
      SzhDWXJ5eVBVaUFQCkxLMXErV0tkVzM0b0lzWUoyVFVsbjA4NW9vUGZBZ01CQUFHalV6QlJNQjBHQTFV
      ZERnUVdCQlFZeEVsQjFwQzAKd3d4THdLSTd4eTZReGNGNEpUQWZCZ05WSFNNRUdEQVdnQlFZeEVsQjFw
      QzB3d3hMd0tJN3h5NlF4Y0Y0SlRBUApCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liM0RRRUJD
      d1VBQTRJQkFRQm9wMWdwRCtWQzNqdTlKVWhTCkI0WTFzWFljeXhEOHJJdHJ6R0VDSDlGSzB0WlJNU2ZC
      OThWZEZySUM0RE11WVdpS0tMWloyVWNXRlhjRUx3Y3YKRUJ1cFBhNHlOamlzWkJEM3AzaG1hMHFPQjFU
      Tlk4N0s5REZrVWgrN2Mvd2xaTlphcmRiZUlKaWRCMDBWYmNLegpnNWJQOTl0SkZMa1kvaXhJaGdwQ0Vl
      TDZaVWFCQmJmcDZzNTZsNG1zcUdWaU85RGxvWnBSV1AyMXJPT1dWMDh3CmgyYi9VNStaeTVBTnNmeDVo
      YUtsajZNcWphbG9DeVZZVktGSERwc2k2c0cxZnF2RjNNYzlWWXJBQmVsZVhGL2IKbnNYMStMWjlFU2py
      d2pwZVV5SkEyVktPTlQyMHVKQUM3dXRybnJGNjRUdVRIeXFCcTRMY1FQMmNHS21BWVVYOApZUVVhCi0t
      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  failurePolicy: Fail
  name: mpod.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: None
