name: unit-tests
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read
  pull-requests: read
jobs:
  unit-test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - uses: actions/checkout@v3
      - name: Run unit tests
        run: |
          go test -v ./...
      - name: Run bdd tests
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo
          go get github.com/onsi/gomega/...
          make test
      - name: Build the binary
        run: |
          make build
          ./op-readiness --dry-run
